[#bifurcacoes]
== Criando bifurcações no projeto

O capítulo anterior mostrou uma mesclagem do tipo
_fast-forward_, que é um tipo sem conflito.
Aqui, veremos como resolver conflitos quando ele acontecem.

=== Criando um ramo comum

Agora faremos uma versão do sistema em alemão.
Para manter uma boa prática de Git vamos criar um novo
ramo, como mostra a figura <<fig:41>>.

.Criando um branch para uma versão em alemão
[[fig:41, {counter:refcde}]]
[source]
----
~/greetings$ git branch de
~/greetings$ git log --oneline --all
2aa634b (HEAD -> main, pt-br, de) versão brasileira parametrizada
8828ea9 versão brasileira
bd61894 (tag: v0.3) verifica se é o programa principal
e0fe2b3 (tag: v0.2) cria função main
933fc74 (origin/main, origin/HEAD) Update README.md
6c8951a cria arquivo greet.py
58da81b Initial commit
~/greetings$ git checkout de
Switched to branch 'de'
----

Para trabalhar no novo ramo, deve-se usar o comando
`git checkout`. O comando `git log`
mostra o ramo para o qual *HEAD* aponta.

Depois de fazer a alteração sugerida na figura <<fig:43>>,
execute o comando `git commit` para deixar 
gravada as alterações no repositório.

.Alteração feita para versão alemã do sistema
[[fig:43, {counter:refcde}]]
[source]
----
~/greetings$ cat greet.py 
import sys
def main():
    if len(sys.argv)>1 and sys.argv[1]=='pt-br':
        print("Olá!")
    elif len(sys.argv)>1 and sys.argv[1]=='de':
        print("Hallo!")
    else:
        print("Hello!")

if __name__ == "__main__":
    main()
----

.Funcionamento depois da versão alemã
[[fig:43a, {counter:refcde}]]
[source]
----
~/greetings$ python greet.py 
Hello!
~/greetings$ python greet.py pt-br
Olá!
~/greetings$ python greet.py de
Hallo!
----

A fotografia do último _commit_ está na figura
<<fig:44>>.

.Fotografando a versão alemã do sistema
[[fig:44, {counter:refcde}]]
[source]
----
~/greetings$ git add greet.py 
~/greetings$ git commit -m 'versão alemã parametrizada'
[de 54a47d0] versão alemã parametrizada
 1 file changed, 2 insertions(+)
----

A figura <<fig:45>> mostra que o sistema possui seis 
fotografias até o momento.

.Listando as fotografias após a inclusão da versão alemã
[[fig:45, {counter:refcde}]]
[source]
----
~/greetings$ git log --oneline --all
54a47d0 (HEAD -> de) versão alemã parametrizada
2aa634b (pt-br, main) versão brasileira parametrizada
8828ea9 versão brasileira
bd61894 (tag: v0.3) verifica se é o programa principal
e0fe2b3 (tag: v0.2) cria função main
933fc74 (origin/main, origin/HEAD) Update README.md
6c8951a cria arquivo greet.py
58da81b Initial commit
----

Na condição atual, no exemplo co capítulo anterior,
o ramo foi mesclado com o ramo estável.
Mas para exemplificar um conflito, não vamos mesclá-lo 
agora.
Um motivo para não mesclar é não ter feito todos os
testes no seu ramo.
Ou o ramo ainda não está terminado.
Vamos supor me nossa situações hipotética que 
não temos certeza que a resposta correta em alemão
é _hallo_.
Por isso, vamos adiar a mesclagem com o ramo principal.


=== Criando mais um ramo comum

Normalmente, conflitos de mesclagem não são criados 
intencionalemente. Mas para ilustrar a resolução 
de conflitos que inevitavelmente acontecerão,
vamos fazer uma versão em italiano do nosso 
sistema para forçar um conflito.
Para isso, vamos começar criando um novo ramo a
partir de *main*.
Após fotografarmos a alteração do sistema
com a versão italiana, teremos dois ramos que
nasceram a partir de *main*.
Um deles é facilmente mesclável. O outro, nem tanto.

Uma forma de se criar um ramo a partir de *main*
é estando com *HEAD* apontando para *main*.
Em seguida, usa-se o comando `git branch` para 
criar um novo branch, como na figura <<fig:46>>.

.Criando um branch para implementar uma versão italiana a partir da versão brasileira
[[fig:46, {counter:refcde}]]
[source]
----
francisco@i7titanv:~/greetings$ git checkout main
Switched to branch 'main'
Your branch is ahead of 'origin/main' by 4 commits.
  (use "git push" to publish your local commits)
francisco@i7titanv:~/greetings$ git branch it
francisco@i7titanv:~/greetings$ git checkout it
Switched to branch 'it'
----

Implemente a alteração sugerida na figura <<fig:48>>.

.Implementando a versão italiana
[[fig:48, {counter:refcde}]]
[source]
----
~/greetings$ cat greet.py 
import sys
def main():
    if len(sys.argv)>1 and sys.argv[1]=='pt-br':
        print("Olá!")
    elif len(sys.argv)>1 and sys.argv[1]=='it':
        print("Ciao!")
    else:
        print("Hello!")

if __name__ == "__main__":
    main()
----

Adicione as alterações na área de stage e execute
o comando `git commit` para fazer a nova fotografia.

Após adicionar as alterações na área de stage e executar
o comando `git commit` a fotografia mais atual
deverá estar parecida com a da figura <<fig:49>>.

.Visualizando a fotografia da versão italiana
[[fig:49, {counter:refcde}]]
[source]
----
francisco@i7titanv:~/greetings$ git add greet.py 
francisco@i7titanv:~/greetings$ git commit -m 'versão italiana parametrizada'
[it 46244be] versão italiana parametrizada
 1 file changed, 2 insertions(+)
francisco@i7titanv:~/greetings$ git log --oneline --all
46244be (HEAD -> it) versão italiana parametrizada
54a47d0 (de) versão alemã parametrizada
2aa634b (pt-br, main) versão brasileira parametrizada
8828ea9 versão brasileira
bd61894 (tag: v0.3) verifica se é o programa principal
e0fe2b3 (tag: v0.2) cria função main
933fc74 (origin/main, origin/HEAD) Update README.md
6c8951a cria arquivo greet.py
58da81b Initial commit
----

=== Listando as fotografias em forma de grafo

A opção `--graph` do comando `git log`
lista as fotografias do repositório em forma de grafo,
como na figura <<fig:50>>.


.Listando todas as fotografias do repositório em forma de grafo
[[fig:50, {counter:refcde}]]
[source]
----
~/greetings$ git log --oneline --all --graph
* 46244be (HEAD -> it) versão italiana parametrizada
| * 54a47d0 (de) versão alemã parametrizada
|/  
* 2aa634b (pt-br, main) versão brasileira parametrizada
* 8828ea9 versão brasileira
* bd61894 (tag: v0.3) verifica se é o programa principal
* e0fe2b3 (tag: v0.2) cria função main
* 933fc74 (origin/main, origin/HEAD) Update README.md
* 6c8951a cria arquivo greet.py
* 58da81b Initial commit
----

Note que acima do ramo *main* as linhas estão
vermelhas, indicando um possível conflito.
Observe que o ramo *de* (alemão), que é mais
antigo que o ramo *it* (italiano), se mostra como
um ramo que está saindo de um galho.


=== Mesclando o último ramo antes do primeiro

O último ramo criado foi o ramo *it*,
mas aqui vasmos mesclá-lo ao ramo principal
antes do ramo mais antigo, que é o ramo *de*.
A figura <<fig:51>> mostra uma forma de como isso 
pode ser feito.
Ocorreu uma mesclagem do tipo _fast-forward_
sem nenhum problema.

.Mesclando a versão italiana com a principal
[[fig:51, {counter:refcde}]]
[source]
----
francisco@i7titanv:~/greetings$ git checkout main
Switched to branch 'main'
Your branch is ahead of 'origin/main' by 4 commits.
  (use "git push" to publish your local commits)
francisco@i7titanv:~/greetings$ git merge it
Updating 2aa634b..46244be
Fast-forward
 greet.py | 2 ++
 1 file changed, 2 insertions(+)
----

Na figura <<fig:52>> podemos ver que o grafo não foi 
alterado, mas agora *HEAD* e *main*
estão na fotografia mais recente.

.Listando todas as fotografias do repositório em forma de grafo após mesclar a versão italiana
[[fig:52, {counter:refcde}]]
[source]
----
~/greetings$ git log --oneline --all --graph
* 46244be (HEAD -> main, it) versão italiana parametrizada
| * 54a47d0 (de) versão alemã parametrizada
|/  
* 2aa634b (pt-br) versão brasileira parametrizada
* 8828ea9 versão brasileira
* bd61894 (tag: v0.3) verifica se é o programa principal
* e0fe2b3 (tag: v0.2) cria função main
* 933fc74 (origin/main, origin/HEAD) Update README.md
* 6c8951a cria arquivo greet.py
* 58da81b Initial commit
----

=== Quando não corre tudo bem na mesclagem

Agora, veja figura <<fig:53>> o que ocorre quando tentamos 
mesclar o ramo alemão com o ramo princial.

.Mesclando a versão alemã com a principal
[[fig:53, {counter:refcde}]]
[source]
----
~/greetings$ git merge de
Auto-merging greet.py
CONFLICT (content): Merge conflict in greet.py
Automatic merge failed; fix conflicts and then commit the result.
----


.Como ficou o arquivo
[[fig:54, {counter:refcde}]]
[source]
----
~/greetings$ cat greet.py 
import sys
def main():
    if len(sys.argv)>1 and sys.argv[1]=='pt-br':
        print("Olá!")
<<<<<<< HEAD
    elif len(sys.argv)>1 and sys.argv[1]=='it':
        print("Ciao!")
=======
    elif len(sys.argv)>1 and sys.argv[1]=='de':
        print("Hallo!")
>>>>>>> de
    else:
        print("Hello!")

if __name__ == "__main__":
    main()
----
Conforme a figura <<fig:54>>, a ferramenta `vimdiff`
pode ser selecionada como na figura <<fig:55>>.

.status
[[fig:55, {counter:refcde}]]
[source]
----
~/greetings$ git status
On branch main
Your branch is ahead of 'origin/main' by 5 commits.
  (use "git push" to publish your local commits)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   greet.py

no changes added to commit (use "git add" and/or "git commit -a")
----

.Como ficou o arquivo
[[fig:56, {counter:refcde}]]
[source]
----
~/greetings$ cat greet.py 
import sys
def main():
    if len(sys.argv)>1 and sys.argv[1]=='pt-br':
        print("Olá!")
    elif len(sys.argv)>1 and sys.argv[1]=='it':
        print("Ciao!")
    elif len(sys.argv)>1 and sys.argv[1]=='de':
        print("Hallo!")
    else:
        print("Hello!")

if __name__ == "__main__":
    main()
----

.Resultado
[[fig:57, {counter:refcde}]]
[source]
----
francisco@i7titanv:~/greetings$ git add greet.py 
francisco@i7titanv:~/greetings$ git commit -m 'merge com versão alemã'
[main 4377f73] merge com versão alemã
francisco@i7titanv:~/greetings$ git log --oneline --all --graph
*   4377f73 (HEAD -> main) merge com versão alemã
|\  
| * 54a47d0 (de) versão alemã parametrizada
* | 46244be (it) versão italiana parametrizada
|/  
* 2aa634b (pt-br) versão brasileira parametrizada
* 8828ea9 versão brasileira
* bd61894 (tag: v0.3) verifica se é o programa principal
* e0fe2b3 (tag: v0.2) cria função main
* 933fc74 (origin/main, origin/HEAD) Update README.md
* 6c8951a cria arquivo greet.py
* 58da81b Initial commit
----

.Programa
[[fig:58, {counter:refcde}]]
[source]
----
~/greetings$ python greet.py 
Hello!
~/greetings$ python greet.py pt-br
Olá!
~/greetings$ python greet.py it
Ciao!
~/greetings$ python greet.py de
Hallo!
----

.Push
[[fig:59, {counter:refcde}]]
[source]
----
~/greetings$ git push
Username for 'https://github.com': fboldt
Password for 'https://fboldt@github.com': 
Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Delta compression using up to 8 threads
Compressing objects: 100% (20/20), done.
Writing objects: 100% (21/21), 2.14 KiB | 2.14 MiB/s, done.
Total 21 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), done.
To https://github.com/fboldt/greetings.git
   933fc74..4377f73  main -> main
----

.Lista final
[[fig60, {counter:refcde}]]
[source]
----
~/greetings$ git log --oneline --all --graph
*   4377f73 (HEAD -> main, origin/main, origin/HEAD) merge com versão alemã
|\  
| * 54a47d0 (de) versão alemã parametrizada
* | 46244be (it) versão italiana parametrizada
|/  
* 2aa634b (pt-br) versão brasileira parametrizada
* 8828ea9 versão brasileira
* bd61894 (tag: v0.3) verifica se é o programa principal
* e0fe2b3 (tag: v0.2) cria função main
* 933fc74 Update README.md
* 6c8951a cria arquivo greet.py
* 58da81b Initial commit
----
